name: dolo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  flutter_svg: ^2.0.9
  cloud_firestore: ^5.6.0
  rxdart: ^0.28.0
  image_picker: ^1.2.0
  firebase_storage: ^12.4.0
  geolocator: ^12.0.0
  permission_handler: ^12.0.1
  location: ^7.0.0
  geocoding: ^4.0.0
  google_places_autocomplete_text_field: ^2.0.3
  google_maps_flutter: ^2.12.3
  flutter_polyline_points: ^2.0.0
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  mime: ^2.0.0
  http_parser: ^4.1.2
  file_picker: ^8.0.7
  flutter_secure_storage: ^9.2.4
  google_places_flutter: ^2.1.1
  device_info_plus: ^10.1.2
  swipe_to: ^1.0.6
  just_audio: ^0.9.40
  tutorial_coach_mark: ^1.2.11
  firebase_messaging: ^15.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/companylogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/
